language: c
sudo: required
services:
  - docker
script: make build
deploy:
  - provider: script
    script: make all
    on:
      all_branches: true
notifications:   
  email:     
    on_success: never 
    on_failure: change
