#!/usr/bin/env python3
import re, sys, os

TITLE_LEN = 72

# Hide the traceback
sys.tracebacklimit = 0

def main():
    pattern = r'(WIP: )?(build|ci|chore|docs|feat|fix|perf|refactor|revert|style|test)(\([\w\-\.]+\))?!?:\s.*'
    filename = sys.argv[1]
    ss = list(filter(lambda x: not x.startswith("#"), [l.strip() for l in open(filename, 'r').readlines()]))
    m = re.match(pattern, "".join(ss))
    if ss[0].startswith('Merge'):
        return
    if (n_chars := len(ss[0])) > TITLE_LEN:
        raise Exception(f"summary {n_chars} not shorter than {TITLE_LEN} chars")
    if m == None:
        raise Exception("conventional commit validation failed")

if __name__ == "__main__":
    main()
