#!/bin/sh
# If you didn't change the CHANGELOG, this script will remind you :)

# destination of the final changelog file
OUTPUT_FILE=CHANGELOG.md

if [ ! -r $OUTPUT_FILE ]; then
  echo "$OUTPUT_FILE not found."
  exit 0
fi

res=$(git show --stat --name-only | grep -c $OUTPUT_FILE)
if [ "$res" -lt 1 ]; then
    OUTPUT=$(git --no-pager log --no-merges --format="- **%aN** %s" -n 1)
    echo "!!!!!!!!!! Did not find an entry in the Changelog ($OUTPUT_FILE) !!!!!!!!!!"
    echo $OUTPUT
    echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
fi
