version: '3.7'

services:
  app:
    image: my-app
    ports:
      - 8080:8080
    entrypoint: [ "tail", "-f", "/dev/null" ]
  db:
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
    environment:
      DB: mydb

volumes:
  db_data:
