# updates homebrew itself:
# 	brew update
# upgrade all individual packages:
# 	brew upgrade
#
# brew bundle install
brew "stow"
brew "cmake"
brew "zip"
brew "tree"
brew "gcc"
brew "llvm"
brew "gsed"
brew "zlib"
brew "git-lfs"
brew "git-delta"
brew "bat"
brew "bat-extras"
brew "subversion"
brew "cvs"
brew "ripgrep"
brew "pgformatter"
brew "postgresql@14"
brew "libpq"
brew "pyenv"
brew "poetry"
brew "rustup"
brew "awscli"
brew "cfn-lint"
brew "yamllint"
brew "codespell"
brew "shellcheck"
brew "httpie"
brew "jq"
brew "yq"
brew "nvm" #nvm install v20
brew "yarn"
brew "typescript"
brew "gitlab-runner"
brew "graphviz"
brew "boxes"
brew "pre-commit"
brew "ffmpeg"
brew "ical-buddy"
brew "neovim"
brew "netcat"
brew "telnet"
brew "nmap"
brew "glab"
brew "task"
brew "timewarrior"
# brew "asyncapi" #< prefer `npm install -g @asyncapi/cli`
# brew "python@3.10"
# brew "python@3.9"
# brew install --cask session-manager-plugin
# brewk install --cask powershell
#brew "node@20"
# brew install --cask iterm2
# brew tap homebrew/cask-fonts
# brew install --cask font-hack-nerd-font
# brew "macvim"
# brew "neovim-qt"
