# Get latest everything:
# 	brew update && brew bundle
#
# updates homebrew itself:
# 	brew update
# upgrade all individual packages:
# 	brew upgrade <package>
#
# brew bundle install
# brew bundle check --debug
# brew bundle cleanup --force

# set arguments for all "brew install --cask" commands
cask_args appdir: "/Applications", no_quarantine: true

# ---------------------------------------------------------------------------------------------------
tap "homebrew/bundle"
tap "buo/cask-upgrade"
# ---------------------------------------------------------------------------------------------------
tap "homebrew/cask-fonts"
cask "font-hack-nerd-font"
# ---------------------------------------------------------------------------------------------------
brew "zsh"
brew "zsh-autosuggestions"
brew "powerlevel10k"
cask "alacritty"
# ---------------------------------------------------------------------------------------------------
brew "coreutils"
brew "stow"
brew "cmake"
brew "zip"
brew "tree"
brew "gcc"
brew "llvm"
brew "gsed"
brew "watch"
brew "zlib"
brew "openjdk"
brew "fd"
brew "fzf"
brew "bat"
brew "bat-extras"
brew "ripgrep"
brew "neovim"
brew "netcat"
brew "telnet"
brew "nmap"
# ---------------------------------------------------------------------------------------------------
brew "gitlab-runner"
brew "gitlab-ci-local"
brew "glab"
brew "gh"
brew "pre-commit"
brew "git-lfs"
brew "git-delta"
brew "cvs"
brew "subversion"
# ---------------------------------------------------------------------------------------------------
brew "httpie"
brew "jq"
brew "yq"
brew "speedtest-cli"
brew "ffmpeg"
cask "postman"
cask "soapui"
cask "devtoys"
cask "docker"
# ---------------------------------------------------------------------------------------------------
brew "plantuml"
brew "graphviz"
brew "boxes"
cask "drawio"
cask "xmind"
# ---------------------------------------------------------------------------------------------------
brew "pgformatter"
brew "postgresql@14"
brew "libpq"
brew "pyenv"
# brew "poetry" # do not install outside pyenv
# brew "python@3.10"
# brew "python@3.9"
brew "cookiecutter"
brew "rustup"
brew "nvm" #nvm install v20
# brew "node@20"
# brew "asyncapi" #< prefer `npm install -g @asyncapi/cli`
brew "prettier"
brew "yarn"
brew "typescript"
brew "golang"
# ---------------------------------------------------------------------------------------------------
brew "awscli", link: true
brew "awslogs"
brew "aws-sso-cli"
cask "session-manager-plugin"
tap "lucagrulla/tap"
brew "lucagrulla/tap/cw" # CloudWatch logs
brew "cfn-lint"
# ---------------------------------------------------------------------------------------------------
brew "stylua"
brew "yamllint"
brew "codespell"
brew "shellcheck"
# ---------------------------------------------------------------------------------------------------
brew "task"
brew "timewarrior"
# ---------------------------------------------------------------------------------------------------
brew "scrcpy"
cask "android-platform-tools"
# ---------------------------------------------------------------------------------------------------
brew "zk", args: ["HEAD"]
cask "obsidian"
cask "vscodium"
cask "chromium"
cask "keepingyouawake"

# brew remove --force $(brew list --formula)
# brew remove --cask --force $(brew list)
