# https://alacritty.org/config-alacritty.html
[shell]
program = "/bin/zsh"
args = ["--login"]

[window]
dimensions = { columns = 132, lines = 43 }

[selection]
semantic_escape_chars=",│`|:\"' ()[]{}<>\t"
save_to_clipboard=true

[font]
normal = { family = "Hack Nerd Font Mono", style = "Regular" }
bold = { family = "Hack Nerd Font Mono", style = "Bold" }
italic = { family = "Hack Nerd Font Mono", style = "Italic" }
bold_italic = { family = "Hack Nerd Font Mono", style = "Bold Italic" }
size = 12

[keyboard]
bindings = [
	{ key = "Key0", mods = "Control", action = "ResetFontSize" },
	{ key = "=", mods = "Control", action = "IncreaseFontSize" },
	{ key = "+", mods = "Control|Shift", action = "IncreaseFontSize" },
	{ key = "-", mods = "Control", action = "DecreaseFontSize" },
	{ key = "_", mods = "Control|Shift", action = "DecreaseFontSize" },
	{ key = "N", mods= "Control|Shift", action= "CreateNewWindow" },
	{ key = "P", mods= "Control|Shift", action= "SpawnNewInstance" },
	{ key = "T", mods="Control|Shift", action="CreateNewTab" },
	{ key = "Left", mods = "Control", action = "SelectPreviousTab" },
	{ key = "Right", mods = "Control", action = "SelectNextTab" },
]
