# https://alacritty.org/config-alacritty.html
[shell]
program = "/bin/zsh"
args = ["--login"]

[window]
dimensions = { columns = 132, lines = 43 }

[selection]
semantic_escape_chars=",│`|:\"' ()[]{}<>\t"
save_to_clipboard=true

[font]
normal = {family= "Hack Nerd Font Mono", style= "Regular" }
size = 12
